#if !canImport(ObjectiveC)
import XCTest

extension PublicSuffixUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PublicSuffixUpdaterTests = [
        ("test_delegate", test_delegate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PublicSuffixUpdaterTests.__allTests__PublicSuffixUpdaterTests),
    ]
}
#endif
