#!/usr/bin/env zsh

function __isTrue() {
  if [[ "${(L)1:-}" == "true" ]]; then
    return 0
  fi
  return 1
}

function __isFalse() {
  if [[ "${(L)1:-}" == "false" ]]; then
    return 0
  fi
  return 1
}

declare -r utilsDir="$(cd "$(dirname "$0")" && pwd -L)"
declare -r updaterPackageDir="${utilsDir}/SwiftPublicSuffixUpdater"
declare scratchPath="$(cd "${utilsDir}/../.build" && pwd -P)"
declare -a swiftCommandArguments=(--package-path "$updaterPackageDir" --scratch-path "$scratchPath")
declare -A parsedArguments=()
zparseopts -D -E -M -A parsedArguments -- \
  b -build=b \
  t -test=t

if [[ -v YOCKOW_USE_LOCAL_PACKAGES ]] && ! __isFalse "$YOCKOW_USE_LOCAL_PACKAGES"; then
  scratchPath="$HOME/.yswift-build"
fi

declare doBuild="false"
if [[ -n "${parsedArguments[(i)-b]}" ]]; then
  doBuild="true"
fi

declare doTest="false"
if [[ -n "${parsedArguments[(i)-t]}" ]]; then
  doTest="true"
fi

if __isTrue "$doBuild"; then
  set -x;
  swift build $swiftCommandArguments
  { set +x; } 2>/dev/null
fi
if __isTrue "$doTest"; then
  set -x;
  swift test $swiftCommandArguments
  { set +x; } 2>/dev/null
fi
if ! __isTrue "$doBuild" && ! __isTrue "$doTest"; then
  set -x;
  swift run $swiftCommandArguments PublicSuffixUpdater
  { set +x; } 2>/dev/null
fi
