#if !canImport(ObjectiveC)
import XCTest

extension PublicSuffixTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PublicSuffixTests = [
        ("test_dummy", test_dummy),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PublicSuffixTests.__allTests__PublicSuffixTests),
    ]
}
#endif
